[config]
version_check = false
caching = false

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.local/state/quickshell/generated/colors.json"
