[config]
version_check = false
caching = false

[config.custom_colors]
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#00ffff"
pink = "#ffc0cb"
orange = "#ffa500"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.local/state/quickshell/generated/colors.json"
post_hook = "bash ~/.config/matugen/scripts/rgb-sync.sh"

[templates.niri]
input_path = "~/.config/matugen/templates/niri-colors.kdl"
output_path = "~/.local/state/niri/generated/colors.kdl"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.local/state/kitty/generated/colors.conf"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty-colors.conf"
output_path = "~/.local/state/ghostty/generated/colors.conf"
