pragma Singleton
import QtQuick

QtObject {
  readonly property string cpu: ""
  readonly property string memory: ""
  readonly property string chip: "\u{f061a}"
  readonly property string harddisk: "\u{f02ca}"
  readonly property string ethernet: ""
  readonly property string monitor: "\u{f0379}"

  readonly property string wifi: ""
  readonly property string wifiOff: "\u{f05aa}"
  readonly property string wifiStrength1: "\u{f091f}"
  readonly property string wifiStrength2: "\u{f0922}"
  readonly property string wifiStrength3: "\u{f0925}"
  readonly property string wifiStrength4: "\u{f0928}"
  readonly property string bluetooth: ""
  readonly property string bluetoothOff: "\u{f00b2}"
  readonly property string arrowUp: "\u{f005d}"
  readonly property string arrowDown: "\u{f0045}"

  readonly property string volumeOff: ""
  readonly property string volumeLow: ""
  readonly property string volumeHigh: ""
  readonly property string volumeMuted: ""
  readonly property string microphone: ""
  readonly property string microphoneOff: ""

  readonly property string brightness: "\u{f00df}"
  readonly property string keyboard: "\u{f030c}"
  readonly property string keyboardOff: "\u{f0310}"

  readonly property string batteryFull: ""
  readonly property string batteryThreeQuarters: ""
  readonly property string batteryHalf: ""
  readonly property string batteryQuarter: ""
  readonly property string batteryEmpty: ""
  readonly property string batteryAlert: "\u{f0083}"
  readonly property string batteryUnknown: "\u{f0091}"
  readonly property string bolt: "\u{f0db3}"
  readonly property string powerPlug: "\u{f06a5}"

  readonly property string lock: ""
  readonly property string unlock: ""
  readonly property string powerOff: ""
  readonly property string restart: "\u{f0709}"
  readonly property string logout: ""
  readonly property string sleep: "\u{f04b2}"
  readonly property string hibernate: "\u{f0904}"

  readonly property string play: ""
  readonly property string pause: ""
  readonly property string stepForward: ""
  readonly property string stepBackward: ""
  readonly property string shuffle: ""
  readonly property string repeat: ""

  readonly property string calendar: ""
  readonly property string chevronLeft: ""
  readonly property string chevronRight: ""
  readonly property string chevronUp: ""
  readonly property string chevronDown: ""
  readonly property string close: ""
  readonly property string check: ""
  readonly property string infoCircle: ""
  readonly property string alertCircle: "\u{f0028}"
  readonly property string gauge: "\u{f029a}"
  readonly property string leaf: ""
  readonly property string rabbit: "\u{f0907}"
  readonly property string turtle: "\u{f0cd7}"
  readonly property string bell: "\u{f009a}"
  readonly property string bellOff: "\u{f009b}"
  readonly property string dotsVertical: "\u{f01d9}"
  readonly property string applicationOutline: "\u{f0614}"
  readonly property string contentCopy: "\u{f018f}"
}
